# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Simple-DTDReader
version:      0.01
version_from: DTDReader.pm
installdirs:  site
requires:
    XML::Parser:                   2.28

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
